### ISSUE TITLE
[ERROR] 'Namespace' object has no attribute 'deepdanbooru_projects_path'

### ISSUE THREAD

**Issue by Zolilio** [GiusTex/vladmandic-WD14-Tagger#1]
When I installed this extention and relaunched Vlad, I got this message in the terminal: 

`│ C:\Users\User\AI\Stable-Diffusion\automatic\modules\script_callbacks.py:161 in ui_tabs_callback                     │
│                                                                                                                      │
│   160 │   │   │   t0 = time.time()                                                                                   │
│ ❱ 161 │   │   │   res += c.callback() or []                                                                          │
│   162 │   │   │   timer(t0, c.script, 'ui_tabs')                                                                     │
│                                                                                                                      │
│ in on_ui_tabs:329                                                                                                    │
│                                                                                                                      │
│   328 │   │   │   │   │   with gr.Row(variant='compact'):                                                            │
│ ❱ 329 │   │   │   │   │   │   interrogator_names = utils.refresh_interrogators()                                     │
│   330 │   │   │   │   │   │   interrogator = utils.preset.component(                                                 │
│                                                                                                                      │
│ in refresh_interrogators:70                                                                                          │
│                                                                                                                      │
│   69 │                                                                                                               │
│ ❱ 70 │   for path in os.scandir(shared.cmd_opts.deepdanbooru_projects_path):                                         │
│   71 │   │   if not path.is_dir():                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'deepdanbooru_projects_path'`

This error was also a problem for the extention for A1111: https://github.com/toriato/stable-diffusion-webui-wd14-tagger/issues/36
Unfortunatly, it's seems that the original author of the extention didn't resolved this problem properly. Can anyone with the same issue can help solving it ?

**Comment by Zolilio** [comment]
Ok. I solved the problem and it seems like the path in automatic/modules/cmd_args.py at line 47 dont work for some reason. Just replace all the `\` in `default="C:\Users\<USER>\.cache\huggingface\hub\models--SmilingWolf--wd-v1-4-vit-tagger-v2\snapshots\1f3f3e8ae769634e31e1ef696df11ec37493e4f2")` with `/`

**Comment by GiusTex** [comment]
Thanks for the feedback. The `/` (or `\\`) instead of `\` is required when one inserts a path. In those days I'll check again if I have to fix something else in the code. Maybe this is caused by old files in my repo (though you said the bug was in `cmd_args.py`, and I didn't change that file)
