### ISSUE TITLE
Doesn't work for SD-Next in 2024 (Updated Vlad fork)

### ISSUE THREAD

**Issue by Klokinator** [GiusTex/vladmandic-WD14-Tagger#2]
I installed this extension after doing a bit of hunting, but unfortunately the extension does not appear inside the current versions of Vladmandic's tabs up top.

![image](https://github.com/GiusTex/vladmandic-WD14-Tagger/assets/30022758/a3739fd2-413e-4f5b-bd7a-01ead926f127)

Hoping you, the dev for this fork, can update it to work. Note that I did refresh and fully restart the engine, just in case.

**Comment by GiusTex** [comment]
I don't use anymore Vladmandic in favor of Auto1111, but I'll see what I can do, probably I'll install one last time Vlad

**Comment by GiusTex** [comment]
I'm sorry, I can't fix it, Vladmandic is no more supported (he removed auto1111/modules/image.py `sanitize_filename_part` parts).
Long explanation: I should change Vladmandic code (in vladmancid/modules/image.py by adding the auto1111/modules/image.py `sanitize_filename_part` parts), but I can't do this every time Vlad updates his code and this isn't suggested, then I tried creating a new file in my extension only with the `sanitize_filename_part` parts, but I got a new error, and I don't know how to fix that one.
I'll update the extension to point out that now it works probably only with auto1111.

**Comment by Klokinator** [comment]
Damn, that's a huge shame. Well, thanks for looking anyway. Much appreciated! I have an Intel Arc 770 so I have no choice but to use Vlad's fork since it's the only one that supports my new GPU natively. Shame the WD tagger doesn't work, maybe I can find an alternative...

**Comment by Klokinator** [comment]
I actually found out that on Civitai, you can upload a bunch of images, auto-tag them, and then download the images and tags back. Then you can edit from there. Seems to be the easiest option for now!

**Comment by GiusTex** [comment]
If you want an online tagger there is also the wd14-tagger from the original author on [Huggingface space](https://huggingface.co/spaces/SmilingWolf/wd-tagger)
